### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by kaycbas** [kaycbas/rocket#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation

**Comment by mkayys** [comment]
# User Auth

## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login
- [x] Should not be able to visit `/signin` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

# Comments
- overall looks amazing! 
- my only suggestions are that when you link to your github and linkedin, personally, it's nice if they open in a new tab
- also, i would reconsider having the login with google option (unless you're going to implement that later); we don't want links that don't do what they say

# Comments Response
-thanks!
-added 404 on bad paths
-re: redux logger: is there a way do this dynamically based on environment? if not, I plan to remove it in the end.
-social media links now open in a new tab
-I'm going to leave in the google option for now because it's looking like I may be ahead of schedule and I might try to implement it. If not, I will change it.

**Comment by mkayys** [comment]
- everything looks good! for the redux logger, I do believe you can have a if/else condition based on the environment being dev or prod
