### ISSUE TITLE
PA Review: Discover Articles (#3)

### ISSUE THREAD

**Issue by kaycbas** [kaycbas/rocket#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
-------
Comments:
-Users should be able to navigate to the discover tab, browse articles, and save them via either the save button on the index page or from within the article
-Saved articles will disappear from the discover tab and appear in the Home tab
-Users can hide articles in the discover tab they are not interested in (hides can be reset from the profile dropdown)

**Comment by mkayys** [comment]
- looks great! I just had a question about one of your comments: "Saved articles will disappear from the discover tab and appear in the Home tab"
- it looks like that doesn't happen until I click the Home tab; wasn't sure if that was supposed to immediate?

**Comment by mkayys** [comment]
- also just a couple things for styling (since you mentioned responsiveness), it looks like some of the later articles are being squished (the save button and text):
![Screen Shot 2020-12-15 at 2 38 36 PM](https://user-images.githubusercontent.com/48598856/102281190-5638e680-3ee3-11eb-9ed9-8edf3d6b478c.png)
- and it looks like there's a lot of white space along the bottom when there aren't any more articles:
![Screen Shot 2020-12-15 at 2 38 51 PM](https://user-images.githubusercontent.com/48598856/102281239-6d77d400-3ee3-11eb-8069-d5be5454c404.png)

**Comment by kaycbas** [comment]
@mkayys 
- I guess my comment above wasn't really what I meant. Saved articles should remain on the Discover page with the red 'Saved' tag until you navigate off the page. Then they disappear and no longer show up on Discover. That's the intended behavior.
- And good catch on the styling. The height is hardcoded atm so it squishes or shows extra white space. I'll fix that.

**Comment by kaycbas** [comment]
Height fixed
